apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-hello
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: "nodejs-hello.{{ .Values.clusterDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-hello
                port:
                  number: 8080

