apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-hello
  name: nodejs-hello
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-hello
status:
  loadBalancer: {}
