apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: private-registry
  name: registry-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30007
  selector:
    app: private-registry
